# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "vkerobS" do |vkerobS|
    vkerobS.vm.box = "generic/alpine319"
    vkerobS.vm.hostname = "vkerobS"
    
    vkerobS.vm.network "private_network", ip: "192.168.56.110", libvirt__network_name: "vagrant-libvirt"

    vkerobS.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 2
    end

    vkerobS.vm.provision "shell", path: "../scripts/install_k3s.sh", args: ["server"]

  end

  config.vm.define "vkerobSW" do |vkerobSW|
    vkerobSW.vm.box = "generic/alpine319"
    vkerobSW.vm.hostname = "vkerobSW"

    vkerobSW.vm.network "private_network", ip: "192.168.56.111", libvirt__network_name: "vagrant-libvirt"
    
    vkerobSW.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 512
      libvirt.cpus = 1
    end

    vkerobSW.vm.provision "shell", path: "../scripts/install_k3s.sh", args: ["worker"]

  end
end