global:
  hosts:
    domain: gitlab.local
    gitlab:
      name: gitlab.local
  ingress:
    enabled: false
  certmanager:
    enabled: false
  certmanager-issuer:
    enabled: false
  kas:
    enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

exporter:
  enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

certmanager-issuer:
  install: false
  email: dev@fake.local

gitlab-runner:
  install: false

prometheus:
  install: false

grafana:
  install: false

kas:
  install: false

