Vagrant.configure("2") do |config|

    config.vm.box = "bento/debian-12"
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    
    config.vm.define "jvasseurS" do |server|
      server.vm.hostname = "jvasseurS"
      server.vm.network "private_network", ip: "192.168.56.110" # IP 
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
      end

    
      # Provisionnement par script externe pour l'installation de K3s en mode serveur
      server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
    
    end
  
  end