Vagrant.configure("2") do |config|

    config.vm.box = "bento/debian-12"
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
    
    config.vm.define "jvasseurS" do |server|
      server.vm.hostname = "jvasseurS"
      server.vm.network "private_network", ip: "192.168.56.110" # IP 
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
      end

    
      # Provisionnement par script externe pour l'installation de K3s en mode serveur
      server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
    
      # Provisionnement supplémentaire pour déployer l'application
      server.vm.provision "shell", inline: <<-SHELL
        # Définir la variable d'environnement KUBECONFIG pour pointer vers le fichier généré par K3s
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml

  
        # Attendre que le serveur K3s soit opérationnel (optionnel : ajustez la durée si besoin)
        sleep 10
  
        echo "Déploiement de app1 via kubectl..."
        # Appliquer les fichiers de déploiement et de service
        # kubectl create configmap app1-config --from-file=/vagrant/confs/app1/app1.html
        kubectl apply -f /vagrant/confs/app1/service.yaml
        kubectl apply -f /vagrant/confs/app1/deployment.yaml

        kubectl apply -f /vagrant/confs/ingress.yaml

      SHELL
    end
  
  end