global:
  hosts:
    domain: gitlab.local
  ingress:
    enabled: false
  certmanager:
    enabled: false
  certmanager-issuer:
    enabled: false
  kas:
    enabled: false
  exporter:
    enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

gitlab-runner:
  install: false

prometheus:
  install: false

gitlab:
  grafana:
    enabled: false
  kas:
    enabled: false
