global:
  hosts:
    domain: gitlab.local
  ingress:
    enabled: false
  certmanager:
    enabled: false
  certmanager-issuer:
    enabled: false


nginx-ingress:
  enabled: false

certmanager:
  install: false

gitlab-runner:
  install: false

certmanager-issuer:
  install: false

prometheus:
  install: false

gitlab:
  grafana:
    enabled: false
  kas:
    enabled: false
  exporter:
    enabled: false
  sidekiq:
    minReplicas: 1
    maxReplicas: 2
    concurrency: 10
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "200m"
        memory: "400Mi"