global:
  hosts:
    domain: gitlab.local
    gitlab:
      name: gitlab.local
  appConfig:
    externalUrl: https://gitlab.local


  ingress:
    enabled: false
  certmanager:
    enabled: false
  certmanager-issuer:
    enabled: false
  kas:
    enabled: false
  exporter:
    enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

gitlab-runner:
  install: false

prometheus:
  install: false

certmanager-issuer:
  enabled: false
  email: dev@fake.local

gitlab:
  grafana:
    enabled: false
  kas:
    enabled: false
