global:
  ingress:
    configureCertmanager: false
    enabled: false
  hosts:
    domain: gitlab.local

gitlab:
  webservice:
    ingress:
      enabled: false
  toolbox:
    ingress:
      enabled: false
  sidekiq:
    ingress:
      enabled: false
  kas:
    ingress:
      enabled: false
  gitlab-shell:
    ingress:
      enabled: false
  grafana:
    ingress:
      enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false
