Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"

  config.vm.define "jvasseurS" do |server|

    server.vm.hostname = "jvasseurS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|

      vb.memory = 1024    
      vb.cpus   = 2

    end

    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"

  end

    config.vm.define "jvasseurSW" do |worker|

      worker.vm.hostname = "jvasseurSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|

      vb.memory = 512   
      vb.cpus   = 1

    end

    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"

  end
end