Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"

  # --- Définition de la machine principal (jvasseurS) ---
  config.vm.define "jvasseurS" do |server|
    server.vm.hostname = "jvasseurS"
    server.vm.network "private_network", ip: "192.168.56.110" # IP 
    server.vm.provider "virtualbox" do |vb|

      # 1 CPU, 512 MB of RAM (subject request)
      vb.memory = 512    
      vb.cpus   = 1

    end

      # Provisionnement par script externe pour l'installation de K3s en mode serveur
      server.vm.provision "shell", path: "scripts/install_k3s_server.sh"

      #Installation de kubectl
      # server.vm.provision "shell", path: "scripts/install_kubectl.sh"
  end

   # --- Définition de la machine server (jvasseurSW) ---
    config.vm.define "jvasseurSW" do |worker|

      worker.vm.hostname = "jvasseurSW"
      worker.vm.network "private_network", ip: "192.168.56.111" # IP
      worker.vm.provider "virtualbox" do |vb|

      # 1 CPU, 512 MB of RAM (subject request)
      vb.memory = 512   
      vb.cpus   = 1

    end

      # Provisionnement par script externe pour l'installation de K3s en mode agent
      worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"

      #Installation de kubectl
      # worker.vm.provision "shell", path: "scripts/install_kubectl.sh"
  end
end